# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(db_index=True, help_text='Metric identifier (e.g., total_revenue, avg_margin_pct)', max_length=200)),
                ('metric_value', models.DecimalField(decimal_places=4, help_text='Numeric metric value', max_digits=20)),
                ('metric_category', models.CharField(choices=[('revenue', 'Revenue'), ('collections', 'Collections'), ('profitability', 'Profitability'), ('leakage', 'Leakage'), ('clients', 'Clients'), ('contracts', 'Contracts'), ('operations', 'Operations'), ('ai', 'AI Performance')], default='revenue', max_length=20)),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Dimension slices (e.g., by client, by segment, by billing_model)')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, help_text='Previous period value for trend calculation', max_digits=20, null=True)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change from previous period', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the metric calculation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metric Snapshot',
                'verbose_name_plural': 'Metric Snapshots',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['organization', 'metric_name', 'period_start'], name='analytics_m_organiz_603a9d_idx'), models.Index(fields=['metric_name', 'period_type'], name='analytics_m_metric__55d8e8_idx'), models.Index(fields=['period_start'], name='analytics_m_period__d61ca4_idx'), models.Index(fields=['metric_category'], name='analytics_m_metric__12ea33_idx')],
                'unique_together': {('organization', 'metric_name', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Specific event type (e.g., invoice.created, contract.approved)', max_length=100)),
                ('event_category', models.CharField(choices=[('user_action', 'User Action'), ('system_event', 'System Event'), ('business_event', 'Business Event'), ('integration', 'Integration Event'), ('error', 'Error Event'), ('performance', 'Performance Event')], default='business_event', max_length=20)),
                ('entity_type', models.CharField(blank=True, default='', help_text='Type of entity involved (e.g., invoice, contract, client)', max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', help_text='ID of the entity involved', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Event payload data')),
                ('session_id', models.CharField(blank=True, default='', help_text='User session identifier', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='web', help_text='Event source (web, api, system, integration)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='users.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event_type'], name='analytics_a_organiz_cf4723_idx'), models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx'), models.Index(fields=['entity_type', 'entity_id'], name='analytics_a_entity__c2ba36_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx'), models.Index(fields=['created_at'], name='analytics_a_created_546677_idx'), models.Index(fields=['event_category'], name='analytics_a_event_c_5ac5bd_idx')],
            },
        ),
    ]
