# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilitySnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('trailing_12m_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('trailing_12m_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('trailing_12m_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=10)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Client rank by profitability within the organization')),
                ('active_contracts', models.PositiveIntegerField(default=0)),
                ('total_headcount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('revenue_per_head', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_snapshots', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profitability Snapshot',
                'verbose_name_plural': 'Profitability Snapshots',
                'ordering': ['-snapshot_date', 'rank'],
                'indexes': [models.Index(fields=['client', 'snapshot_date'], name='profitabili_client__9e2900_idx'), models.Index(fields=['snapshot_date', 'rank'], name='profitabili_snapsho_27ef34_idx'), models.Index(fields=['trend_direction'], name='profitabili_trend_d_279830_idx'), models.Index(fields=['trailing_12m_margin_pct'], name='profitabili_trailin_42849e_idx')],
                'unique_together': {('client', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='OverheadAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_overhead', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocation_method', models.CharField(choices=[('revenue_based', 'Revenue-Based'), ('headcount', 'Headcount-Based'), ('equal', 'Equal Distribution'), ('hours_based', 'Hours-Based'), ('custom', 'Custom Formula')], default='revenue_based', max_length=20)),
                ('allocations', models.JSONField(default=dict, help_text='Breakdown of allocations per client/contract as JSON')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overhead_allocations', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overhead Allocation',
                'verbose_name_plural': 'Overhead Allocations',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='profitabili_period__3b33ec_idx'), models.Index(fields=['allocation_method'], name='profitabili_allocat_ad2aee_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarginCalculation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('direct_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocated_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, help_text='Revenue - Direct Costs', max_digits=15)),
                ('gross_margin_pct', models.DecimalField(decimal_places=2, default=0, help_text='Gross margin percentage', max_digits=7, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('net_margin', models.DecimalField(decimal_places=2, default=0, help_text='Revenue - Direct Costs - Overhead', max_digits=15)),
                ('net_margin_pct', models.DecimalField(decimal_places=2, default=0, help_text='Net margin percentage', max_digits=7, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('watch', 'Watch'), ('at_risk', 'At Risk'), ('critical', 'Critical')], default='healthy', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_calculations', to='clients.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin_calculations', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Margin Calculation',
                'verbose_name_plural': 'Margin Calculations',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['client', 'period_start'], name='profitabili_client__7c6266_idx'), models.Index(fields=['contract', 'period_start'], name='profitabili_contrac_4c744a_idx'), models.Index(fields=['status'], name='profitabili_status_6ab872_idx'), models.Index(fields=['gross_margin_pct'], name='profitabili_gross_m_87299c_idx'), models.Index(fields=['net_margin_pct'], name='profitabili_net_mar_99528d_idx')],
                'unique_together': {('client', 'contract', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('direct_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('direct_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('subcontractor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('technology_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocated_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('headcount', models.DecimalField(decimal_places=2, default=0, help_text='FTE headcount allocated', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='clients.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Allocation',
                'verbose_name_plural': 'Cost Allocations',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['client', 'period_start'], name='profitabili_client__2f66cb_idx'), models.Index(fields=['contract', 'period_start'], name='profitabili_contrac_1fe74a_idx'), models.Index(fields=['period_start', 'period_end'], name='profitabili_period__fcfd35_idx')],
                'unique_together': {('client', 'contract', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='BenchmarkData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Period this benchmark applies to')),
                ('billing_model', models.CharField(help_text='Billing model code this benchmark is for', max_length=50)),
                ('industry', models.CharField(blank=True, default='', help_text='Industry segment for this benchmark', max_length=50)),
                ('avg_margin', models.DecimalField(decimal_places=2, help_text='Average margin percentage', max_digits=7)),
                ('median_margin', models.DecimalField(decimal_places=2, help_text='Median margin percentage', max_digits=7)),
                ('top_quartile', models.DecimalField(decimal_places=2, help_text='Top quartile (75th percentile) margin', max_digits=7)),
                ('bottom_quartile', models.DecimalField(decimal_places=2, help_text='Bottom quartile (25th percentile) margin', max_digits=7)),
                ('client_count', models.PositiveIntegerField(default=0, help_text='Number of clients in this benchmark sample')),
                ('data_source', models.CharField(blank=True, default='internal', help_text='Source of benchmark data', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benchmark Data',
                'verbose_name_plural': 'Benchmark Data',
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['period', 'billing_model'], name='profitabili_period_a9eeaf_idx'), models.Index(fields=['industry'], name='profitabili_industr_d0bf70_idx')],
                'unique_together': {('period', 'billing_model', 'industry')},
            },
        ),
    ]
