# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingBucket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField(db_index=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount not yet due', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_30', models.DecimalField(decimal_places=2, default=0, help_text='Amount overdue 1-30 days', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_60', models.DecimalField(decimal_places=2, default=0, help_text='Amount overdue 31-60 days', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_90', models.DecimalField(decimal_places=2, default=0, help_text='Amount overdue 61-90 days', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_90_plus', models.DecimalField(decimal_places=2, default=0, help_text='Amount overdue 90+ days', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('client_count', models.PositiveIntegerField(default=0)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aging Bucket',
                'verbose_name_plural': 'Aging Buckets',
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.CreateModel(
            name='CashForecast',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(db_index=True, help_text='Date when forecast was generated')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('expected_collections', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_collections', models.DecimalField(decimal_places=2, default=0, help_text='Actual collections (populated after period ends)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence level as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('methodology', models.CharField(choices=[('historical', 'Historical Pattern'), ('ai_predicted', 'AI Predicted'), ('weighted_average', 'Weighted Average'), ('manual', 'Manual Estimate'), ('contractual', 'Contractual Schedule')], default='historical', max_length=20)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown by client/invoice')),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between expected and actual (post-period)', max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Cash Forecast',
                'verbose_name_plural': 'Cash Forecasts',
                'ordering': ['-forecast_date', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('as_needed', 'As Needed')], default='weekly', max_length=20)),
                ('next_followup_date', models.DateField(db_index=True)),
                ('escalation_level', models.IntegerField(choices=[(1, 'Level 1 - Standard'), (2, 'Level 2 - Escalated'), (3, 'Level 3 - Management'), (4, 'Level 4 - Legal')], default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_contact_outcome', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Collection Schedule',
                'verbose_name_plural': 'Collection Schedules',
                'ordering': ['next_followup_date'],
            },
        ),
        migrations.CreateModel(
            name='DunningRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('days_overdue', models.PositiveIntegerField(help_text='Number of days overdue to trigger this rule')),
                ('action', models.CharField(choices=[('email', 'Send Email'), ('sms', 'Send SMS'), ('call', 'Schedule Call'), ('escalate', 'Escalate'), ('letter', 'Send Letter'), ('suspend', 'Suspend Services')], max_length=20)),
                ('auto_execute', models.BooleanField(default=False, help_text='Automatically execute action without manual approval')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = higher priority')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Dunning Rule',
                'verbose_name_plural': 'Dunning Rules',
                'ordering': ['days_overdue', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_mode', models.CharField(choices=[('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('wire', 'Wire Transfer'), ('card', 'Credit/Debit Card'), ('dd', 'Demand Draft'), ('other', 'Other')], default='neft', max_length=10)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Payment reference/transaction number', max_length=100)),
                ('bank_reference', models.CharField(blank=True, default='', help_text='Bank statement reference', max_length=100)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Outstanding receivable amount', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('overdue_30', 'Overdue 1-30 Days'), ('overdue_60', 'Overdue 31-60 Days'), ('overdue_90', 'Overdue 61-90 Days'), ('overdue_90_plus', 'Overdue 90+ Days'), ('collected', 'Collected'), ('written_off', 'Written Off'), ('disputed', 'Disputed')], db_index=True, default='current', max_length=20)),
                ('aging_days', models.IntegerField(default=0, help_text='Number of days past due date')),
                ('last_reminder_date', models.DateField(blank=True, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receivable',
                'verbose_name_plural': 'Receivables',
                'ordering': ['-due_date'],
            },
        ),
    ]
