# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_mgmt', '0002_initial'),
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dunningrule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dunning_rules', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='dunningrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_schedules', to='clients.client'),
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashforecast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashforecast',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_forecasts', to='users.organization'),
        ),
        migrations.AddField(
            model_name='cashforecast',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agingbucket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agingbucket',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aging_buckets', to='users.organization'),
        ),
        migrations.AddField(
            model_name='agingbucket',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['client', 'status'], name='collections_client__00f58a_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['due_date'], name='collections_due_dat_72303e_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['status'], name='collections_status_1f3dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['aging_days'], name='collections_aging_d_ef1dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['next_action_date'], name='collections_next_ac_ea6504_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['receivable'], name='collections_receiva_aecf07_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['payment_date'], name='collections_payment_4bfb22_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['reconciled'], name='collections_reconci_85b414_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['reference_number'], name='collections_referen_8fb974_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningrule',
            index=models.Index(fields=['days_overdue', 'is_active'], name='collections_days_ov_d15afe_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningrule',
            index=models.Index(fields=['action'], name='collections_action_029d54_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningrule',
            index=models.Index(fields=['organization'], name='collections_organiz_673db8_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionschedule',
            index=models.Index(fields=['client'], name='collections_client__33276e_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionschedule',
            index=models.Index(fields=['next_followup_date'], name='collections_next_fo_a615ea_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionschedule',
            index=models.Index(fields=['assigned_to'], name='collections_assigne_e18582_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionschedule',
            index=models.Index(fields=['escalation_level'], name='collections_escalat_8e2765_idx'),
        ),
        migrations.AddIndex(
            model_name='cashforecast',
            index=models.Index(fields=['organization', 'forecast_date'], name='collections_organiz_312226_idx'),
        ),
        migrations.AddIndex(
            model_name='cashforecast',
            index=models.Index(fields=['period_start', 'period_end'], name='collections_period__0249fb_idx'),
        ),
        migrations.AddIndex(
            model_name='cashforecast',
            index=models.Index(fields=['methodology'], name='collections_methodo_0e5876_idx'),
        ),
        migrations.AddIndex(
            model_name='agingbucket',
            index=models.Index(fields=['organization', 'as_of_date'], name='collections_organiz_044234_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agingbucket',
            unique_together={('organization', 'as_of_date')},
        ),
    ]
