# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nlp', 'Natural Language Processing'), ('anomaly', 'Anomaly Detection'), ('recommendation', 'Recommendation'), ('forecasting', 'Forecasting'), ('clustering', 'Clustering')], max_length=20)),
                ('endpoint', models.URLField(blank=True, default='', help_text='API endpoint for model inference', max_length=500)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Model configuration parameters')),
                ('is_active', models.BooleanField(default=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=4, help_text='Model accuracy score (0-1)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('failed', 'Failed'), ('staging', 'Staging')], default='staging', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('training_data_info', models.JSONField(blank=True, default=dict, help_text='Information about training data')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Model performance metrics')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['-last_trained'],
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField(default=dict, help_text='Input features/data used for prediction')),
                ('output_data', models.JSONField(default=dict, help_text='Prediction output/result')),
                ('confidence', models.DecimalField(decimal_places=4, help_text='Prediction confidence (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('prediction_type', models.CharField(choices=[('churn_risk', 'Churn Risk'), ('payment_delay', 'Payment Delay'), ('revenue_forecast', 'Revenue Forecast'), ('margin_trend', 'Margin Trend'), ('leakage_risk', 'Leakage Risk'), ('contract_value', 'Contract Value Prediction'), ('collection_date', 'Collection Date')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(blank=True, default='', help_text='Type of entity (client, contract, invoice, etc.)', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', help_text='ID of the entity being predicted', max_length=255)),
                ('actual_outcome', models.JSONField(blank=True, default=dict, help_text='Actual outcome for model validation')),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether prediction was correct (populated after outcome)', null=True)),
            ],
            options={
                'verbose_name': 'AI Prediction',
                'verbose_name_plural': 'AI Predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('reprice', 'Repricing'), ('expand', 'Expansion Opportunity'), ('restructure', 'Restructure'), ('exit', 'Exit/Terminate'), ('optimize', 'Optimize Operations'), ('upsell', 'Upsell'), ('retention', 'Retention Action'), ('risk_mitigation', 'Risk Mitigation')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('expected_impact_amount', models.DecimalField(decimal_places=2, default=0, help_text='Expected financial impact (positive = revenue gain)', max_digits=15)),
                ('expected_impact_pct', models.DecimalField(decimal_places=2, default=0, help_text='Expected percentage impact', max_digits=7)),
                ('confidence_score', models.DecimalField(decimal_places=4, help_text='AI confidence score (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, default='', help_text='AI model version that generated this', max_length=100)),
                ('reasoning', models.JSONField(blank=True, default=dict, help_text='Detailed reasoning/factors as JSON')),
                ('action_items', models.JSONField(blank=True, default=list, help_text='Suggested action items')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('implementation_notes', models.TextField(blank=True, default='')),
                ('actual_impact_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual financial impact after implementation', max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField(blank=True, default='')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens consumed (prompt + response)')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Response latency in milliseconds')),
                ('cost', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_logs', to='ai_engine.aimodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Log',
                'verbose_name_plural': 'Prompt Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractParsing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, default='', help_text='Raw extracted text from document')),
                ('extracted_entities', models.JSONField(blank=True, default=dict, help_text='Extracted entities (dates, amounts, parties, etc.)')),
                ('confidence_scores', models.JSONField(blank=True, default=dict, help_text='Confidence scores per extracted field')),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('processing_time_ms', models.PositiveIntegerField(default=0, help_text='Processing time in milliseconds')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=15)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('corrections', models.JSONField(blank=True, default=dict, help_text='Manual corrections applied after review')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Parsing',
                'verbose_name_plural': 'Contract Parsings',
                'ordering': ['-created_at'],
            },
        ),
    ]
