# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparsing',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsings', to='contracts.contractdocument'),
        ),
        migrations.AddField(
            model_name='contractparsing',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parsings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractparsing',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_engine.aimodel'),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['model', 'created_at'], name='ai_engine_p_model_i_0ba53c_idx'),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['user', 'created_at'], name='ai_engine_p_user_id_860cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['status'], name='ai_engine_p_status_f35bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='promptlog',
            index=models.Index(fields=['created_at'], name='ai_engine_p_created_4a9a26_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparsing',
            index=models.Index(fields=['document'], name='ai_engine_c_documen_52c073_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparsing',
            index=models.Index(fields=['status'], name='ai_engine_c_status_39b292_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparsing',
            index=models.Index(fields=['model_version'], name='ai_engine_c_model_v_105eca_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['client', 'status'], name='ai_engine_a_client__ef5c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['contract', 'status'], name='ai_engine_a_contrac_2910d7_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['recommendation_type', 'status'], name='ai_engine_a_recomme_0bdfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['priority', 'status'], name='ai_engine_a_priorit_aa3a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['generated_at'], name='ai_engine_a_generat_10558d_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['confidence_score'], name='ai_engine_a_confide_5e2d67_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['model', 'prediction_type'], name='ai_engine_a_model_i_457244_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['prediction_type'], name='ai_engine_a_predict_1761f2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['entity_type', 'entity_id'], name='ai_engine_a_entity__35db43_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['created_at'], name='ai_engine_a_created_ec9c64_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['confidence'], name='ai_engine_a_confide_bbc4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['name', 'version'], name='ai_engine_a_name_c68b20_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_type', 'is_active'], name='ai_engine_a_model_t_51576a_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['status'], name='ai_engine_a_status_593792_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('name', 'version')},
        ),
    ]
