# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short code for the billing model (e.g., TM, FP, RET)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Billing rules engine configuration as JSON')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Billing Model',
                'verbose_name_plural': 'Billing Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('locked', 'Locked'), ('invoiced', 'Invoiced')], default='open', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('total_billable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Billing Period',
                'verbose_name_plural': 'Billing Periods',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('milestone', 'Milestone-Based'), ('on_demand', 'On Demand')], default='monthly', max_length=20)),
                ('next_billing_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('generated', 'Generated'), ('skipped', 'Skipped'), ('overdue', 'Overdue')], default='scheduled', max_length=20)),
                ('milestone_description', models.TextField(blank=True, default='', help_text='Description if frequency is milestone-based')),
                ('last_generated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Billing Schedule',
                'verbose_name_plural': 'Billing Schedules',
                'ordering': ['next_billing_date'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('escalation_type', models.CharField(choices=[('annual', 'Annual Fixed'), ('cpi', 'Consumer Price Index'), ('custom', 'Custom Formula'), ('performance', 'Performance-Based')], default='annual', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Escalation percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('frequency', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('on_renewal', 'On Renewal')], default='annual', max_length=20)),
                ('next_escalation_date', models.DateField(db_index=True)),
                ('last_applied', models.DateField(blank=True, null=True)),
                ('auto_apply', models.BooleanField(default=False, help_text='Automatically apply escalation when due')),
                ('cap_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cumulative escalation cap', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Escalation Rule',
                'verbose_name_plural': 'Escalation Rules',
                'ordering': ['next_escalation_date'],
            },
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar')], default='INR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Cards',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RateCardItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text='Role/designation (e.g., Senior Developer, QA Lead)', max_length=200)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for overtime hours (e.g., 1.5x)', max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('minimum_hours', models.DecimalField(decimal_places=2, default=0, help_text='Minimum billable hours per period', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.ratecard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate Card Item',
                'verbose_name_plural': 'Rate Card Items',
                'ordering': ['role_name'],
            },
        ),
    ]
