# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contracts', '0001_initial'),
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_schedules', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_billing_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null means system-wide billing model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_models', to='users.organization'),
        ),
        migrations.AddField(
            model_name='billingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratecarditem',
            index=models.Index(fields=['rate_card', 'role_name'], name='billing_rat_rate_ca_ecebdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratecarditem',
            unique_together={('rate_card', 'role_name')},
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['client', 'status'], name='billing_rat_client__14a226_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['effective_from', 'effective_to'], name='billing_rat_effecti_4dfd67_idx'),
        ),
        migrations.AddIndex(
            model_name='ratecard',
            index=models.Index(fields=['contract'], name='billing_rat_contrac_a0b4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationrule',
            index=models.Index(fields=['contract', 'escalation_type'], name='billing_esc_contrac_0d1c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationrule',
            index=models.Index(fields=['next_escalation_date'], name='billing_esc_next_es_d94f13_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationrule',
            index=models.Index(fields=['auto_apply'], name='billing_esc_auto_ap_b782ad_idx'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['contract', 'status'], name='billing_bil_contrac_2a4b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['next_billing_date'], name='billing_bil_next_bi_fcdd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['frequency'], name='billing_bil_frequen_2a34a8_idx'),
        ),
        migrations.AddIndex(
            model_name='billingperiod',
            index=models.Index(fields=['contract', 'status'], name='billing_bil_contrac_d909a7_idx'),
        ),
        migrations.AddIndex(
            model_name='billingperiod',
            index=models.Index(fields=['period_start', 'period_end'], name='billing_bil_period__e39a5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingperiod',
            unique_together={('contract', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='billingmodel',
            index=models.Index(fields=['code'], name='billing_bil_code_a1a261_idx'),
        ),
        migrations.AddIndex(
            model_name='billingmodel',
            index=models.Index(fields=['is_active'], name='billing_bil_is_acti_e24fca_idx'),
        ),
    ]
