from .templates import (
    CONTRACT_EXTRACTION_PROMPT,
    LEAKAGE_ANALYSIS_PROMPT,
    RECOMMENDATION_PROMPT,
    REVENUE_FORECAST_PROMPT,
    INVOICE_VALIDATION_PROMPT,
    CLIENT_HEALTH_PROMPT,
    MARGIN_INSIGHT_PROMPT,
)

__all__ = [
    "CONTRACT_EXTRACTION_PROMPT",
    "LEAKAGE_ANALYSIS_PROMPT",
    "RECOMMENDATION_PROMPT",
    "REVENUE_FORECAST_PROMPT",
    "INVOICE_VALIDATION_PROMPT",
    "CLIENT_HEALTH_PROMPT",
    "MARGIN_INSIGHT_PROMPT",
]
