# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('bfsi', 'Banking, Financial Services & Insurance'), ('healthcare', 'Healthcare'), ('retail', 'Retail & E-Commerce'), ('manufacturing', 'Manufacturing'), ('telecom', 'Telecommunications'), ('media', 'Media & Entertainment'), ('energy', 'Energy & Utilities'), ('education', 'Education'), ('government', 'Government'), ('automotive', 'Automotive'), ('pharma', 'Pharmaceuticals'), ('real_estate', 'Real Estate'), ('logistics', 'Logistics & Transportation'), ('other', 'Other')], default='technology', max_length=20)),
                ('gstin', models.CharField(blank=True, default='', help_text='Goods and Services Tax Identification Number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('pan', models.CharField(blank=True, default='', help_text='Permanent Account Number', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-character PAN.', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('immediate', 'Immediate'), ('advance', 'Advance')], default='net_30', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Risk score (0-100, higher = more risky)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health_score', models.DecimalField(decimal_places=2, default=75.0, help_text='Health score (0-100, higher = healthier)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive'), ('churned', 'Churned'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.organization')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Segmentation criteria as structured JSON')),
                ('min_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Minimum revenue threshold for this segment', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum revenue threshold (null = unlimited)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('color_code', models.CharField(blank=True, default='#3B82F6', help_text='Hex color for UI display', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Segment',
                'verbose_name_plural': 'Client Segments',
                'ordering': ['min_revenue'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_primary', models.BooleanField(default=False)),
                ('is_billing_contact', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('registered', 'Registered Office'), ('billing', 'Billing Address'), ('shipping', 'Shipping Address'), ('branch', 'Branch Office'), ('warehouse', 'Warehouse')], default='registered', max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gstin', models.CharField(blank=True, default='', help_text='State-specific GSTIN for this address', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Address',
                'verbose_name_plural': 'Client Addresses',
                'ordering': ['-is_default', 'address_type'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.clientsegment'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clientsegment',
            index=models.Index(fields=['name'], name='clients_cli_name_87a4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsegment',
            index=models.Index(fields=['min_revenue', 'max_revenue'], name='clients_cli_min_rev_2a9863_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'is_primary'], name='clients_cli_client__b632ac_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['email'], name='clients_cli_email_030d36_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['client', 'address_type'], name='clients_cli_client__2484c3_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaddress',
            index=models.Index(fields=['state'], name='clients_cli_state_1f00cb_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'status'], name='clients_cli_organiz_bb5819_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['industry'], name='clients_cli_industr_522683_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['gstin'], name='clients_cli_gstin_c1b1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['risk_score'], name='clients_cli_risk_sc_6a75ca_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['health_score'], name='clients_cli_health__1b7bb9_idx'),
        ),
    ]
