# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('tally', 'Tally'), ('sap', 'SAP'), ('salesforce', 'Salesforce'), ('zoho', 'Zoho'), ('jira', 'Jira'), ('freshdesk', 'Freshdesk'), ('excel', 'Excel Import/Export'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero'), ('hubspot', 'HubSpot'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('google_sheets', 'Google Sheets')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', help_text='Custom name for this integration instance', max_length=200)),
                ('config', models.JSONField(default=dict, help_text='Integration configuration (encrypted sensitive fields)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='daily', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('configuring', 'Configuring'), ('suspended', 'Suspended')], default='configuring', max_length=15)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('sync_mappings', models.JSONField(blank=True, default=dict, help_text='Field mappings between systems')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Config',
                'verbose_name_plural': 'Integration Configs',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=200)),
                ('key_prefix', models.CharField(blank=True, default='', help_text='First few characters of key for identification', max_length=10)),
                ('key_hash', models.CharField(help_text='Hashed API key value', max_length=255, unique=True)),
                ('permissions', models.JSONField(default=list, help_text='List of permission scopes granted to this key')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Key expiration date (null = never expires)', null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('rate_limit', models.PositiveIntegerField(default=1000, help_text='Requests per hour limit')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list, help_text='List of event types to trigger this webhook')),
                ('secret', models.CharField(blank=True, default='', help_text='Webhook signing secret for verification', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers to include in webhook requests')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed (Too Many Errors)')], default='active', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Configs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='integration_organiz_d4dcbd_idx'), models.Index(fields=['status'], name='integration_status_74963d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('delta', 'Delta Sync'), ('manual', 'Manual Trigger')], default='incremental', max_length=15)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (Pull)'), ('outbound', 'Outbound (Push)'), ('bidirectional', 'Bidirectional')], default='inbound', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error details')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success'), ('cancelled', 'Cancelled')], default='started', max_length=15)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Summary of what was synced')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integrationconfig')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['integration', 'status'], name='integration_integra_68a376_idx'), models.Index(fields=['started_at'], name='integration_started_633e63_idx'), models.Index(fields=['status'], name='integration_status_bf366b_idx'), models.Index(fields=['sync_type'], name='integration_sync_ty_43f075_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['organization', 'provider'], name='integration_organiz_c2f188_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['provider', 'is_active'], name='integration_provide_333e43_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['status'], name='integration_status_72bbec_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['last_sync'], name='integration_last_sy_010d08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('organization', 'provider', 'name')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'is_active'], name='integration_organiz_7f6ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash'], name='integration_key_has_89bafe_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['status'], name='integration_status_181cef_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['expires_at'], name='integration_expires_475e48_idx'),
        ),
    ]
