# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be recognized', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('recognized_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount recognized to date', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('deferred_amount', models.DecimalField(decimal_places=2, default=0, help_text='Deferred revenue balance', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pattern', models.CharField(choices=[('straight_line', 'Straight Line'), ('percentage_completion', 'Percentage of Completion'), ('milestone', 'Milestone-Based'), ('usage', 'Usage-Based'), ('output', 'Output Method'), ('input', 'Input Method')], default='straight_line', max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_schedules', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('performance_obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_schedules', to='contracts.performanceobligation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Schedule',
                'verbose_name_plural': 'Revenue Schedules',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this entry (can be negative for reversals)', max_digits=15)),
                ('entry_type', models.CharField(choices=[('recognized', 'Revenue Recognized'), ('deferred', 'Deferred Revenue'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('catch_up', 'Catch-Up Adjustment')], default='recognized', max_length=20)),
                ('journal_entry_ref', models.CharField(blank=True, default='', help_text='Reference to accounting journal entry', max_length=100)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_revenue_entries', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='recognition.revenueschedule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Entry',
                'verbose_name_plural': 'Revenue Entries',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('billing_model', models.CharField(help_text='Billing model code this rule applies to', max_length=50)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Conditions under which this rule applies (JSON)')),
                ('recognition_pattern', models.CharField(choices=[('straight_line', 'Straight Line'), ('percentage_completion', 'Percentage of Completion'), ('milestone', 'Milestone-Based'), ('usage', 'Usage-Based'), ('output', 'Output Method'), ('input', 'Input Method')], max_length=25)),
                ('timing', models.CharField(choices=[('over_time', 'Over Time'), ('point_in_time', 'Point in Time')], default='over_time', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recognition Rule',
                'verbose_name_plural': 'Recognition Rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ASC606Compliance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step1_identified', models.BooleanField(default=False, help_text='Step 1: Contract with customer identified')),
                ('step1_notes', models.TextField(blank=True, default='')),
                ('step1_date', models.DateField(blank=True, null=True)),
                ('step2_obligations_identified', models.BooleanField(default=False, help_text='Step 2: Performance obligations identified')),
                ('step2_notes', models.TextField(blank=True, default='')),
                ('step2_date', models.DateField(blank=True, null=True)),
                ('step3_price_determined', models.BooleanField(default=False, help_text='Step 3: Transaction price determined')),
                ('step3_notes', models.TextField(blank=True, default='')),
                ('step3_date', models.DateField(blank=True, null=True)),
                ('step4_allocated', models.BooleanField(default=False, help_text='Step 4: Transaction price allocated to obligations')),
                ('step4_notes', models.TextField(blank=True, default='')),
                ('step4_date', models.DateField(blank=True, null=True)),
                ('step5_recognized', models.BooleanField(default=False, help_text='Step 5: Revenue recognized when/as obligations satisfied')),
                ('step5_notes', models.TextField(blank=True, default='')),
                ('step5_date', models.DateField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('needs_review', 'Needs Review')], default='not_started', max_length=20)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asc606_compliance', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asc606_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ASC 606 Compliance',
                'verbose_name_plural': 'ASC 606 Compliances',
                'ordering': ['-last_review_date'],
            },
        ),
        migrations.AddIndex(
            model_name='revenueschedule',
            index=models.Index(fields=['contract', 'status'], name='recognition_contrac_2265e6_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueschedule',
            index=models.Index(fields=['performance_obligation'], name='recognition_perform_6beca4_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueschedule',
            index=models.Index(fields=['pattern'], name='recognition_pattern_6705b0_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueschedule',
            index=models.Index(fields=['start_date', 'end_date'], name='recognition_start_d_80c126_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['schedule', 'entry_type'], name='recognition_schedul_c1c85a_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['period_start', 'period_end'], name='recognition_period__6f92c7_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['status'], name='recognition_status_5146df_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueentry',
            index=models.Index(fields=['posted_date'], name='recognition_posted__88881b_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrule',
            index=models.Index(fields=['billing_model'], name='recognition_billing_ae76a3_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrule',
            index=models.Index(fields=['recognition_pattern'], name='recognition_recogni_3a131a_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrule',
            index=models.Index(fields=['is_active'], name='recognition_is_acti_7fd742_idx'),
        ),
        migrations.AddIndex(
            model_name='asc606compliance',
            index=models.Index(fields=['compliance_status'], name='recognition_complia_514ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='asc606compliance',
            index=models.Index(fields=['last_review_date'], name='recognition_last_re_48f261_idx'),
        ),
    ]
