# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Dashboard layout configuration')),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this dashboard is visible to all org users')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Auto-refresh interval in seconds (0 = no auto-refresh)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='users.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('revenue', 'Revenue Report'), ('profitability', 'Profitability Report'), ('aging', 'Aging Report'), ('leakage', 'Leakage Report'), ('client_health', 'Client Health Report'), ('collection', 'Collection Report'), ('contract', 'Contract Report'), ('billing', 'Billing Report'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('query_config', models.JSONField(default=dict, help_text='Data query configuration (models, filters, aggregations)')),
                ('columns', models.JSONField(default=list, help_text='Column definitions (name, field, width, format)')),
                ('filters', models.JSONField(blank=True, default=list, help_text='Available filter parameters')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('sort_config', models.JSONField(blank=True, default=dict, help_text='Default sort configuration')),
                ('grouping', models.JSONField(blank=True, default=list, help_text='Grouping/subtotal configuration')),
                ('chart_config', models.JSONField(blank=True, default=dict, help_text='Chart/visualization configuration if applicable')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=15)),
                ('next_run', models.DateTimeField(db_index=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses or user IDs to send report to')),
                ('is_active', models.BooleanField(default=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report parameters/filters for scheduled run')),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('format', models.CharField(default='pdf', max_length=10)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parameters used to generate this report')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='generating', max_length=15)),
                ('error_message', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the file will be automatically deleted', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.reporttemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI Card'), ('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('table', 'Table'), ('heatmap', 'Heatmap'), ('gauge', 'Gauge'), ('trend', 'Trend Indicator'), ('list', 'List'), ('map', 'Map'), ('custom', 'Custom Component')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration (data source, formatting, etc.)')),
                ('position_x', models.PositiveIntegerField(default=0, help_text='Grid X position')),
                ('position_y', models.PositiveIntegerField(default=0, help_text='Grid Y position')),
                ('width', models.PositiveIntegerField(default=4, help_text='Widget width in grid units', validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(default=3, help_text='Widget height in grid units', validators=[django.core.validators.MinValueValidator(1)])),
                ('refresh_interval', models.PositiveIntegerField(default=0, help_text='Widget-specific refresh interval (0 = use dashboard default)')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboard')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'report_type'], name='reports_rep_organiz_5f73c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active'], name='reports_rep_is_acti_4b0ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template', 'is_active'], name='reports_rep_templat_dd64a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run'], name='reports_rep_next_ru_8865e3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency'], name='reports_rep_frequen_1e97ea_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['template', 'generated_at'], name='reports_rep_templat_088b05_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['generated_by'], name='reports_rep_generat_fb5228_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['status'], name='reports_rep_status_fcd648_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['generated_at'], name='reports_rep_generat_6f36a4_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard', 'widget_type'], name='reports_das_dashboa_b67a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['position_x', 'position_y'], name='reports_das_positio_70efa0_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['organization', 'is_default'], name='reports_das_organiz_8d1977_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['owner'], name='reports_das_owner_i_2c0495_idx'),
        ),
    ]
