# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(db_index=True, help_text='Unique contract identifier (e.g., CTR-2024-001)', max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('billing_model', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('time_and_material', 'Time & Material'), ('retainer', 'Retainer'), ('milestone', 'Milestone-Based'), ('hybrid', 'Hybrid'), ('outcome_based', 'Outcome-Based'), ('subscription', 'Subscription')], default='time_and_material', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar')], default='INR', max_length=3)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total contract value', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, help_text='Monthly recurring value', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_term_months', models.PositiveIntegerField(default=12, help_text='Auto-renewal term in months')),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('immediate', 'Immediate'), ('advance', 'Advance')], default='net_30', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('on_hold', 'On Hold'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], db_index=True, default='draft', max_length=20)),
                ('asc606_compliant', models.BooleanField(default=False, help_text='Whether contract has been evaluated for ASC 606 compliance')),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceObligation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('standalone_price', models.DecimalField(decimal_places=2, help_text='Standalone selling price for allocation', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('allocation_amount', models.DecimalField(decimal_places=2, help_text='Allocated transaction price', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('recognition_pattern', models.CharField(choices=[('over_time', 'Over Time'), ('point_in_time', 'Point in Time')], default='over_time', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('satisfied', 'Satisfied'), ('partially_satisfied', 'Partially Satisfied')], default='pending', max_length=20)),
                ('satisfaction_criteria', models.TextField(blank=True, default='', help_text='Criteria for determining when obligation is satisfied')),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_obligations', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Obligation',
                'verbose_name_plural': 'Performance Obligations',
                'ordering': ['contract', 'description'],
                'indexes': [models.Index(fields=['contract', 'status'], name='contracts_p_contrac_8eeb80_idx'), models.Index(fields=['recognition_pattern'], name='contracts_p_recogni_eb113a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('changes_summary', models.TextField()),
                ('effective_date', models.DateField()),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of contract state at this version')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Version',
                'verbose_name_plural': 'Contract Versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['contract', 'version_number'], name='contracts_c_contrac_3870a8_idx')],
                'unique_together': {('contract', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_type', models.CharField(choices=[('payment', 'Payment Term'), ('sla', 'Service Level Agreement'), ('penalty', 'Penalty Clause'), ('termination', 'Termination Clause'), ('renewal', 'Renewal Term'), ('escalation', 'Escalation Clause'), ('warranty', 'Warranty'), ('indemnity', 'Indemnity'), ('confidentiality', 'Confidentiality')], max_length=20)),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('escalation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Escalation rate as percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('escalation_frequency', models.CharField(blank=True, choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('on_renewal', 'On Renewal')], default='', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Term',
                'verbose_name_plural': 'Contract Terms',
                'ordering': ['term_type'],
                'indexes': [models.Index(fields=['contract', 'term_type'], name='contracts_c_contrac_4e7623_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('sow', 'Statement of Work'), ('amendment', 'Amendment'), ('po', 'Purchase Order'), ('nda', 'Non-Disclosure Agreement'), ('msa', 'Master Service Agreement'), ('invoice', 'Invoice'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField(max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='AI-extracted structured data from document')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='AI extraction confidence (0-1)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Document',
                'verbose_name_plural': 'Contract Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'document_type'], name='contracts_c_contrac_ad138f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('effective_date', models.DateField()),
                ('value_change', models.DecimalField(decimal_places=2, default=0, help_text='Positive for increase, negative for decrease', max_digits=15)),
                ('new_terms', models.JSONField(blank=True, default=dict, help_text='Modified terms as structured JSON')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_amendments', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Amendment',
                'verbose_name_plural': 'Contract Amendments',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['contract', 'status'], name='contracts_c_contrac_758618_idx'), models.Index(fields=['effective_date'], name='contracts_c_effecti_0a009e_idx')],
                'unique_together': {('contract', 'amendment_number')},
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status'], name='contracts_c_organiz_ebd2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client', 'status'], name='contracts_c_client__c0be66_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_f953e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['billing_model'], name='contracts_c_billing_330157_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contracts_c_contrac_876f48_idx'),
        ),
    ]
