# Generated by Django 4.2.11 on 2026-07-18 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakageDetection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_type', models.CharField(choices=[('unbilled_hours', 'Unbilled Hours'), ('missed_milestone', 'Missed Milestone'), ('rate_escalation_missed', 'Rate Escalation Missed'), ('expenses_not_billed', 'Expenses Not Billed'), ('scope_creep', 'Scope Creep'), ('undercharging', 'Undercharging'), ('discount_overuse', 'Discount Overuse'), ('contract_expiry_missed', 'Contract Expiry Missed'), ('billing_delay', 'Billing Delay')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Estimated leakage amount', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('escalated', 'Escalated')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('evidence_data', models.JSONField(blank=True, default=dict, help_text='Supporting data/evidence for the detection')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leakage_detections', to='clients.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leakage_detections', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leakage_detections', to='users.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_leakages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leakage Detection',
                'verbose_name_plural': 'Leakage Detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='LeakageRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detection_type', models.CharField(choices=[('unbilled_hours', 'Unbilled Hours'), ('missed_milestone', 'Missed Milestone'), ('rate_escalation_missed', 'Rate Escalation Missed'), ('expenses_not_billed', 'Expenses Not Billed'), ('scope_creep', 'Scope Creep'), ('undercharging', 'Undercharging'), ('discount_overuse', 'Discount Overuse'), ('contract_expiry_missed', 'Contract Expiry Missed'), ('billing_delay', 'Billing Delay')], max_length=30)),
                ('condition', models.JSONField(default=dict, help_text='Rule conditions as structured JSON')),
                ('threshold', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount threshold for triggering', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_alert', models.BooleanField(default=True, help_text='Automatically send alerts when triggered')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours to wait before re-triggering for same entity')),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leakage_rules', to='users.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leakage Rule',
                'verbose_name_plural': 'Leakage Rules',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeakageResolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_taken', models.CharField(choices=[('invoice_generated', 'Invoice Generated'), ('rate_corrected', 'Rate Corrected'), ('contract_amended', 'Contract Amended'), ('credit_note', 'Credit Note Issued'), ('write_off', 'Written Off'), ('no_action', 'No Action Required'), ('process_improvement', 'Process Improvement')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('preventive_measures', models.TextField(blank=True, default='', help_text='Steps taken to prevent recurrence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='leakage.leakagedetection')),
                ('invoice_generated', models.ForeignKey(blank=True, help_text='Invoice generated to recover leaked amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leakage_resolutions', to='invoices.invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leakage Resolution',
                'verbose_name_plural': 'Leakage Resolutions',
                'ordering': ['-recovery_date'],
            },
        ),
        migrations.AddField(
            model_name='leakagedetection',
            name='rule',
            field=models.ForeignKey(blank=True, help_text='Rule that triggered this detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='leakage.leakagerule'),
        ),
        migrations.AddField(
            model_name='leakagedetection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeakageAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notification'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('webhook', 'Webhook')], max_length=20)),
                ('recipients', models.JSONField(default=list, help_text='List of recipient identifiers (emails, user IDs, etc.)')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('delivery_status', models.CharField(default='pending', help_text='Delivery status from notification provider', max_length=20)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_leakage_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='leakage.leakagedetection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leakage Alert',
                'verbose_name_plural': 'Leakage Alerts',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leakagerule',
            index=models.Index(fields=['detection_type', 'is_active'], name='leakage_lea_detecti_13eb47_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagerule',
            index=models.Index(fields=['severity'], name='leakage_lea_severit_2951d8_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagerule',
            index=models.Index(fields=['organization'], name='leakage_lea_organiz_08b0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='leakageresolution',
            index=models.Index(fields=['action_taken'], name='leakage_lea_action__52882c_idx'),
        ),
        migrations.AddIndex(
            model_name='leakageresolution',
            index=models.Index(fields=['recovery_date'], name='leakage_lea_recover_a9dcad_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagedetection',
            index=models.Index(fields=['organization', 'status'], name='leakage_lea_organiz_be55f6_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagedetection',
            index=models.Index(fields=['client', 'detection_type'], name='leakage_lea_client__8b83fd_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagedetection',
            index=models.Index(fields=['contract', 'status'], name='leakage_lea_contrac_06e120_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagedetection',
            index=models.Index(fields=['severity', 'status'], name='leakage_lea_severit_d491b3_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagedetection',
            index=models.Index(fields=['detected_at'], name='leakage_lea_detecte_b913c2_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagealert',
            index=models.Index(fields=['detection'], name='leakage_lea_detecti_94a3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagealert',
            index=models.Index(fields=['alert_type'], name='leakage_lea_alert_t_61a89a_idx'),
        ),
        migrations.AddIndex(
            model_name='leakagealert',
            index=models.Index(fields=['sent_at'], name='leakage_lea_sent_at_6f2cf4_idx'),
        ),
    ]
